In [2]:
'Hello,World'

'Hello,World'

In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [5]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:
c = np.array([[[1,2],[2,3]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [2 3]]

 [[5 6]
  [7 8]]]


In [7]:

np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [8]:
# reshape
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [9]:
# np.ones and np.zeros

np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.random.random((3,4))

array([[0.72545787, 0.72881077, 0.82793361, 0.71455355],
       [0.28630395, 0.58850965, 0.5362872 , 0.78193044],
       [0.14745157, 0.61794988, 0.28929326, 0.64848848]])

In [12]:
# (starting, ending, how many range).....distance between 2 points are same
np.linspace(-10,10,10, dtype=int)


array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [13]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Numpy atribuits

In [14]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3  = np.arange(8).reshape(2,2,2)

In [15]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [16]:
a3.ndim

3

In [17]:
a1.ndim

1

In [18]:
a2.ndim

2

In [19]:
a1.shape

(10,)

In [20]:
a2.shape

(3, 4)

In [21]:
a3.shape

(2, 2, 2)

In [22]:
a2.size
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [23]:
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [24]:
a3.itemsize

8

### Changing Datatype

In [25]:
a3.dtype

dtype('int64')

In [26]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [27]:
# array operations

a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [29]:
a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [30]:
a1-2

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [31]:
a1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [32]:
a2==15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [33]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [35]:
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [36]:
a1/a2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

In [37]:
a1**a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

In [38]:
np.max(a1)

np.int64(11)

In [39]:
np.sum(a1)

np.int64(66)

In [40]:
np.prod(a1, axis=0)

array([  0,  45, 120, 231])

In [41]:
np.median(a1)

np.float64(5.5)

In [42]:
np.var(a1, axis=0)

array([10.66666667, 10.66666667, 10.66666667, 10.66666667])

In [43]:
np.sin(a1)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021]])

In [44]:
np.cos(a1)

array([[ 1.        ,  0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029,  0.75390225],
       [-0.14550003, -0.91113026, -0.83907153,  0.0044257 ]])

In [45]:
np.tan(a1)

array([[ 0.00000000e+00,  1.55740772e+00, -2.18503986e+00,
        -1.42546543e-01],
       [ 1.15782128e+00, -3.38051501e+00, -2.91006191e-01,
         8.71447983e-01],
       [-6.79971146e+00, -4.52315659e-01,  6.48360827e-01,
        -2.25950846e+02]])

In [46]:
np.exp(a1)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [47]:
np.round(np.random.random((2,3))*100)

array([[56., 64., 81.],
       [ 6.,  7., 23.]])

In [48]:
np.floor(np.random.random((2,3))*100)

array([[10., 50., 46.],
       [50.,  7., 47.]])

In [49]:
np.ceil(np.random.random((2,3))*100)

array([[13., 87.,  6.],
       [47., 78., 87.]])